DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

aha_greenhouse/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from apps.forum.views import index

from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls'),),  # 环境监测
    path('user/', include('user.urls'),),  # 用户管理
    path('control/', include('controller.urls'), ),  # 用户管理
    path('forum/', include('forum.urls'), ),  # 用户管理
    path('ueditor/', include('DjangoUeditor.urls')),  # 添加DjangoUeditor的URL
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 增加此行
    path('', index, name='index'),  # 环境监测
]

apps/controller/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.controller.views import change_status, device_control, control_plan, create_plan, control_history


app_name = 'control'
urlpatterns = [
    path('change_status/', change_status, name='change_status'),
    path('device_control/', device_control, name='device_control'),
    path('control_plan/', control_plan, name='control_plan'),
    path('device_control/create_plan/', create_plan, name='create_plan'),
    path('control_history/', control_history, name='control_history'),
]

apps/monitor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.monitor.views import index, detail, get_data, query_environmentdata, add_data, analysis


app_name = 'monitor'
urlpatterns = [
    path('', index, name='index'),   # 监控首页
    path('<int:house_id>/', detail, name='detail'),  # 大棚详情页
    path('<int:house_id>/get_data/', get_data, name='get_data'),   # 获取实时数据
    path('query/environment_data/', query_environmentdata, name='environment_data'),  # 查询环境数据
    path('add_data/', add_data, name='add_data'),  # 数据接口
    path('analysis/', analysis, name='analysis'),  # 折线图
]

apps/controller/models.py
from django.db import models
from apps.monitor.models import Device, EnvironmentIndicator

# Create your models here.


class DeviceControl(models.Model):
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    status = models.CharField('控制状态', max_length=10, default='启动')
    control_type = models.IntegerField('控制方式', default=1)   # 1-手动，2-阈值，3-定时，4-预约
    control_id = models.IntegerField('控制信息', null=True)   # 对应的control表的id

    class Meta:
        verbose_name = '设备控制表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数

    def __str__(self):
        return self.device.name


class DeviceOrder(models.Model):
    name = models.CharField('指令名称', max_length=100)
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    path = models.CharField('路径', max_length=100)
    parameter = models.CharField('参数', max_length=100)

    class Meta:
        verbose_name = '设备指令表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数

    def __str__(self):
        return self.name


class ThresholdControl(models.Model):
    name = models.CharField('指令名称', max_length=100)
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    indicator = models.ForeignKey(EnvironmentIndicator, on_delete=models.DO_NOTHING, verbose_name='环境指标', blank=True, null=True)
    threshold = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='阈值')
    order = models.ForeignKey(DeviceOrder, on_delete=models.DO_NOTHING, verbose_name='设备指令', blank=True, null=True)

    class Meta:
        verbose_name = '阈值控制表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数


class BookControl(models.Model):
    name = models.CharField('指令名称', max_length=100)
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    order = models.ForeignKey(DeviceOrder, on_delete=models.DO_NOTHING, verbose_name='设备指令', blank=True, null=True)
    start_time = models.DateTimeField('开始时间')
    stop_time = models.DateTimeField('结束时间')

    class Meta:
        verbose_name = '预约控制表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数


class TimerControl(models.Model):
    name = models.CharField('指令名称', max_length=100)
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    order = models.ForeignKey(DeviceOrder, on_delete=models.DO_NOTHING, verbose_name='设备指令', blank=True, null=True)
    start_time = models.DateTimeField('开始时间')
    stop_time = models.DateTimeField('结束时间')
    repeat_type = models.CharField('重复方式', max_length=10, default='不重复')   # 0-不重复，1-每天，2-每2天

    class Meta:
        verbose_name = '定时控制表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数


class ControlHistory(models.Model):
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING, verbose_name='设备名称', blank=True, null=True)
    order = models.ForeignKey(DeviceOrder, on_delete=models.DO_NOTHING, verbose_name='设备指令', blank=True, null=True)
    control_type = models.IntegerField('控制方式')
    create_time = models.DateTimeField('操作时间', auto_now_add=True)

    class Meta:
        verbose_name = '设备命令表'  # 可读的名字
        verbose_name_plural = verbose_name  # 可读的名字的复数

    # def __str__(self):
    #     return self.control_type

apps/controller/views.py
from django.shortcuts import render, redirect, reverse
from apps.controller.models import Device, DeviceControl, DeviceOrder, ControlHistory, ThresholdControl, TimerControl, BookControl
from django.http import HttpResponse, JsonResponse
from datetime import datetime

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def change_status(request):
    if request.POST:
        try:
            device_id = request.POST.get('device_id')
            order = request.POST.get('order')
            type_id = request.POST.get('type_id')
            order_id = DeviceOrder.objects.filter(device_id=device_id, name=order).last().id
            flag = control_simulator(device_id, order, order_id, type_id)
            if flag:
                device = DeviceControl.objects.get(device_id=device_id)
                device.status = order
                device.save()
                return JsonResponse({'status': '1'}, json_dumps_params={'ensure_ascii': False})
        except Exception as e:
            return JsonResponse({'status': '0'}, json_dumps_params={'ensure_ascii': False})
    return JsonResponse({'status': '0'}, json_dumps_params={'ensure_ascii': False})


def control_simulator(device_id, order, order_id, control_type):
    try:
        print('{}设备{}中'.format(order, Device.objects.get(id=device_id).name))
        history = ControlHistory(device_id=device_id, order_id=order_id, control_type=control_type)
        history.save()
        print('增加了控制记录')
        return 1
    except:
        return


from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


def device_control(request):
    if request.user.is_authenticated:
        devices = DeviceControl.objects.all()
        # todo:动态获取设备前十条操作记录
        history = ControlHistory.objects.all()[:10]
        control_dict = {
            1: '手动',
            2: '阈值',
            3: '定时',
            4: '预约',
        }
        return render(request, 'controller/device_control.html', locals())
    else:
        return redirect(reverse('user:login'))


def create_plan(request):
    if request.POST:
        device_id = request.POST.get('device_id')
        controltype = int(request.POST.get('controltype'))
        threshold_name = request.POST.get('threshold-name')
        indicator = request.POST.get('indicator')
        threshold = request.POST.get('threshold')
        book_name = request.POST.get('book-name')
        book_start = datetime.strptime(request.POST.get('book-start'), '%Y/%m/%d %H:%M:%S')
        book_stop = datetime.strptime(request.POST.get('book-stop'), '%Y/%m/%d %H:%M:%S')
        timer_name = request.POST.get('timer-name')
        timer_start = datetime.strptime(request.POST.get('timer-start'), '%Y/%m/%d %H:%M:%S')
        timer_stop = datetime.strptime(request.POST.get('timer-stop'), '%Y/%m/%d %H:%M:%S')
        timer_repeat = request.POST.get('timer-repeat')
        print(threshold_name, book_name, controltype)
        # try:
        p1 = ThresholdControl(name=threshold_name, device_id=device_id, indicator_id=indicator, threshold=threshold)
        p2 = BookControl(name=book_name, device_id=device_id, start_time=book_start, stop_time=book_stop)
        p3 = TimerControl(name=timer_name, device_id=device_id, start_time=timer_start, stop_time=timer_stop, repeat_type=timer_repeat)
        p1.save()
        p2.save()
        p3.save()
        d = DeviceControl.objects.get(device_id=device_id)
        d.control_type = controltype
        d.save()
        return redirect(reverse('control:device_control'))
        # except Exception as e:
        #     return redirect(reverse('control:device_control'))


def control_history(request):
    pass


def control_plan(request):
    pass

templates/controller/device_control.html
{% extends 'base_content.html' %}
{% load static%}
{% block top-css %}
    <link rel="stylesheet" href="{% static 'css/monitor-1.css' %}"/>
<style>
    .customers {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    .customers td, .customers th {
      border: 1px solid #ddd;
      padding: 8px;
      text-align:center;
    }

    .customers tr:nth-child(even){background-color: #f2f2f2;}

     tr:hover {background-color: #ddd;}

     th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #0f9960cc;
      color: white;
    }

</style>
{% endblock top-css %}

<!--右侧内容开始-->
{% block right-content %}
<div class="col-xs-10">
    <br/>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;主页</a></li>
        <li class="active">大棚管理 - 设备控制 </li>
    </ol>
    <div class="xuanze" style="margin-left: 15%;margin-top: 50px">
    <div class="select_place">
        <h4>设备列表：</h4>
                <table class="customers" >
                    <tr>
                        <th>大棚名称</th>
                        <th>设备名称</th>
                        <th>设备位置</th>
                        <th>手动启停</th>
<!--                        <th>设备状态</th>-->
                        <th>控制方式</th>
                        <th>控制历史</th>
                        <th>控制修改</th>

                    </tr>
                    {% for d in devices %}
                    <tr>
                        <td><a href="{% url 'monitor:index' %}{{device.id}}">{{ d.device.greenhouse.name }}</td>
                        <td>{{ d.device.name }}</td>
                        <td>{{ d.device.location }}</td>
                        <td class="peopel_control">
                            {% ifequal d.status '启动' %}
                            <input class="button-img" id="{{ d.device_id }}"  type="image" src="{% static 'img/kaiguan3.png' %}">
                            {% else %}
                            <input class="button-img" id="{{ d.device_id }}"  type="image" src="{% static 'img/kaiguan4.png' %}">
                            {% endifequal %}
                        </td>
<!--                        <td>{{ d.status }}</td>-->
                        <td>{{ control_dict|get_item:d.control_type }}</td>
                        <td><a href="#" data-toggle="modal" data-target="#controlHistory">控制历史</a>
                        </td>
                        <td><a href="#" data-toggle="modal" data-target="#createPlan">修改控制信息</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr><td colspan = "7">No date yet.</td></tr>
                    {% endfor %}
                </table>
        <div class="modal fade" id="controlHistory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="controlHistoryLabel">控制历史</h4>
                    </div>
                    <div class="modal-body">
                        <table class="customers" >
                    <tr>
                        <th>设备名称</th>
                        <th>指令</th>
                        <th>操作类型</th>
                        <th>操作时间</th>
                    </tr>
                    {% for h in history %}
                    <tr>
                        <td>{{ h.device.name }}</td>
                        <td>{{ h.order.name }}</td>
                        <td>{{ control_dict|get_item:h.control_type }}</td>
                        <td>{{ h.create_time }}</td>
                    </tr>
                    {% empty %}
                    <tr><td colspan = "7">No date yet.</td></tr>
                    {% endfor %}
                </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="createPlan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <form method="post" action="create_plan/">
                {% csrf_token %}
                <input type="text" name="device_id" value="37" display="none">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="createPlanLabel">修改控制信息</h4>
                    </div>
                    <div class="modal-body">
                        <input type="radio" name="controltype" value="2" checked="checked">阈值
                        <input type="radio" name="controltype" value="3">预约
                        <input type="radio" name="controltype" value="4">定时
                        <input type="radio" name="controltype" value="1">手动
                        <hr>
                        <div class="threshold">
                            <h4>阈值计划</h4>
                            计划名称：<input type="text" name="threshold-name" value="温度控制计划1"><br>
                            指标：<select name="indicator">
                            {% for i in indicator_list %}
                                <option value="{{ i.id }}">{{ i.name }}</option>
                            {% endfor %}
                                </select><br>
                            阈值：<input type="text" name="threshold" value="25.5"><br>
                            指令：<select name="order">
                                    <option value="启动">启动</option>
                                    <option value="停止">停止</option>
                                    <option value="关闭">关闭</option>
                                </select>
                        </div>
                        <hr>
                        <div class="book">
                            <h4>预约计划</h4>
                            计划名称：<input type="text" name="book-name" value="预约控制计划1"><br>
                            开始时间：<input type="text" name="book-start" value="2021/05/07 10:00:00"><br>
                            结束时间：<input type="text" name="book-stop" value="2021/05/07 10:30:00"><br>
                            指令：<select name="order">
                                    <option value="">启动</option>
                                    <option value="">停止</option>
                                    <option value="">关闭</option>
                                </select>
                        </div>
                        <hr>
                        <div class="timer">
                            <h4>定时计划</h4>
                            计划名称：<input type="text" name="timer-name" value="定时控制计划1"><br>
                            启动时间：<input type="text" name="timer-start" value="2021/05/07 10:00:00"><br>
                            结束时间：<input type="text" name="timer-stop" value="2021/05/07 10:30:00"><br>
                            重复周期：<input type="text" name="timer-repeat" value="每天"><br>
                            指令：<select name="order">
                                    <option value="">启动</option>
                                    <option value="">停止</option>
                                    <option value="">关闭</option>
                                </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-primary" >保存</button>
                    </div>
                </div>
            </div>
                </form>
        </div>
    </div>
        </select>
    </div>
    <div>
</div>
{% endblock right-content %}
<!--右侧内容结束-->

{% block bottom-script %}
<script>
    $(".button-img").click(function() {
        device_id = $(this).attr("id")
        if ($(this).attr("src")== "/static/img/kaiguan3.png"){
            $(this).attr("src", "/static/img/kaiguan4.png");
            params = {
                'device_id':device_id,
                'order':"关闭",
                'type_id':1
                };
                $.post('{% url 'control:change_status' %}', params, function (data) {
                status=data.status});

<!--                window.location.reload();-->
        }
        else {
            $(this).attr("src", "/static/img/kaiguan3.png");
            params = {
            'device_id':device_id,
            'order':"启动",
            'type_id':1
                };
            $.post('{% url 'control:change_status' %}', params, function (data) {
                status = data.status});
<!--                window.location.reload();-->
        };
        } )


</script>
{% endblock bottom-script %}

templates/controller/device_control_new.html
{% extends 'base_content.html' %}
{% load static%}
{% block top-css %}
    <link rel="stylesheet" href="{% static 'css/monitor-1.css' %}"/>
<style>
    .customers {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    .customers td, .customers th {
      border: 1px solid #ddd;
      padding: 8px;
      text-align:center;
    }

    .customers tr:nth-child(even){background-color: #f2f2f2;}

     tr:hover {background-color: #ddd;}

     th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #0f9960cc;
      color: white;
    }
        #toggle-button{ display: none; }
        .button-label{
            position: relative;
            display: inline-block;
            width: 70px;
            height: 20px;
            background-color: #ccc;
            box-shadow: #ccc 0px 0px 0px 2px;
            border-radius: 20px;
            overflow: hidden;
        }
        .circle{
            position: absolute;
            top: 0;
            left: 0;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            background-color: #fff;
        }
        .button-label .text {
            line-height: 20px;
            font-size: 12px;
            text-shadow: 0 0 2px #ddd;
        }

        .on { color: #fff; display: none; text-indent: 0px;}
        .off { color: #fff; display: inline-block; text-indent: 16px;}
        .button-label .circle{
            left: 0;
            transition: all 0.3s;
        }
        #toggle-button:checked + label.button-label .circle{
            left: 50px;
        }
        #toggle-button:checked + label.button-label .on{ display: inline-block; }
        #toggle-button:checked + label.button-label .off{ display: none; }
        #toggle-button:checked + label.button-label{
            background-color: #0f9960;
</style>
{% endblock top-css %}

<!--右侧内容开始-->
{% block right-content %}
<div class="col-xs-10">
    <br/>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;主页</a></li>
        <li class="active">大棚管理 - 设备控制 </li>
    </ol>
    <div class="xuanze" style="margin-left: 15%;margin-top: 50px">
    <div class="select_place">
        <h4>设备列表：</h4>
                <table class="customers" >
                    <tr>
                        <th>大棚名称</th>
                        <th>设备名称</th>
                        <th>设备位置</th>
                        <th>手动启停</th>
                        <th>控制方式</th>
                        <th>控制历史</th>
                        <th>控制修改</th>

                    </tr>
                    {% for d in devices %}
                    <tr>
                        <td><a href="{% url 'monitor:index' %}{{device.id}}">{{ d.device.greenhouse.name }}</td>
                        <td>{{ d.device.name }}</td>
                        <td>{{ d.device.location }}</td>
                        <td class="peopel_control">
<!--                            <input class="button-img" id="{{ d.device_id }}" type="image" src="{% static 'img/kaiguan3.png' %}">-->
                        <div class="toggle-button-wrapper">
                        <input type="checkbox" id="toggle-button" name="switch" >
                        <label for="toggle-button" class="button-label">
                            <span class="circle"></span>
                            <span class="text on">ON</span>
                            <span class="text off">OFF</span>
                        </label>
                        </div>
                        </td>
                        <td>{{ control_dict|get_item:d.control_type }}</td>
                        <td><a href="#" data-toggle="modal" data-target="#controlHistory">控制历史</a>
                        </td>
                        <td><a href="#" data-toggle="modal" data-target="#createPlan">修改控制信息</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr><td colspan = "7">No date yet.</td></tr>
                    {% endfor %}
                </table>
        <div class="modal fade" id="controlHistory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="controlHistoryLabel">控制历史</h4>
                    </div>
                    <div class="modal-body">
                        <table class="customers" >
                    <tr>
                        <th>设备名称</th>
                        <th>指令</th>
                        <th>操作类型</th>
                        <th>操作时间</th>
                    </tr>
                    {% for h in history %}
                    <tr>
                        <td>{{ h.device.name }}</td>
                        <td>{{ h.order.name }}</td>
                        <td>{{ control_dict|get_item:h.control_type }}</td>
                        <td>{{ h.create_time }}</td>
                    </tr>
                    {% empty %}
                    <tr><td colspan = "7">No date yet.</td></tr>
                    {% endfor %}
                </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="createPlan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <form method="post" action="create_plan/">
                {% csrf_token %}
                <input type="text" name="device_id" value="37" display="none">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="createPlanLabel">修改控制信息</h4>
                    </div>
                    <div class="modal-body">
                        <input type="radio" name="controltype" value="2" checked="checked">阈值
                        <input type="radio" name="controltype" value="3">预约
                        <input type="radio" name="controltype" value="4">定时
                        <input type="radio" name="controltype" value="1">手动
                        <hr>
                        <div class="threshold">
                            <h4>阈值计划</h4>
                            计划名称：<input type="text" name="threshold-name" value="温度控制计划1"><br>
                            指标：<select name="indicator">
                            {% for i in indicator_list %}
                                <option value="{{ i.id }}">{{ i.name }}</option>
                            {% endfor %}
                                </select><br>
                            阈值：<input type="text" name="threshold" value="25.5"><br>
                            指令：<select name="order">
                                    <option value="启动">启动</option>
                                    <option value="停止">停止</option>
                                    <option value="关闭">关闭</option>
                                </select>
                        </div>
                        <hr>
                        <div class="book">
                            <h4>预约计划</h4>
                            计划名称：<input type="text" name="book-name" value="预约控制计划1"><br>
                            开始时间：<input type="text" name="book-start" value="2021/05/07 10:00:00"><br>
                            结束时间：<input type="text" name="book-stop" value="2021/05/07 10:30:00"><br>
                            指令：<select name="order">
                                    <option value="">启动</option>
                                    <option value="">停止</option>
                                    <option value="">关闭</option>
                                </select>
                        </div>
                        <hr>
                        <div class="timer">
                            <h4>定时计划</h4>
                            计划名称：<input type="text" name="timer-name" value="定时控制计划1"><br>
                            启动时间：<input type="text" name="timer-start" value="2021/05/07 10:00:00"><br>
                            结束时间：<input type="text" name="timer-stop" value="2021/05/07 10:30:00"><br>
                            重复周期：<input type="text" name="timer-repeat" value="每天"><br>
                            指令：<select name="order">
                                    <option value="">启动</option>
                                    <option value="">停止</option>
                                    <option value="">关闭</option>
                                </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-primary" >保存</button>
                    </div>
                </div>
            </div>
                </form>
        </div>
    </div>
        </select>
    </div>
    <div>
</div>
{% endblock right-content %}
<!--右侧内容结束-->

{% block bottom-script %}
<script>

    $('#toggle-button').click(function () {
        alert('修改成功');
        var device=37;
        var order='启动';
        var type=1;

        $.POST("{% url 'control:change_status' %}",{
        device:37,
        order:"启动",
        type:1
        })
        );

</script>
{% endblock bottom-script %}