DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

aha_greenhouse/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from apps.forum.views import index

from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls'),),  # 环境监测
    path('user/', include('user.urls'),),  # 用户管理
    path('control/', include('controller.urls'), ),  # 用户管理
    path('forum/', include('forum.urls'), ),  # 用户管理
    path('ueditor/', include('DjangoUeditor.urls')),  # 添加DjangoUeditor的URL
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 增加此行
    path('', index, name='index'),  # 环境监测
]

apps/controller/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.controller.views import change_status, device_control, control_plan, create_plan, control_history


app_name = 'control'
urlpatterns = [
    path('change_status/', change_status, name='change_status'),
    path('device_control/', device_control, name='device_control'),
    path('control_plan/', control_plan, name='control_plan'),
    path('device_control/create_plan/', create_plan, name='create_plan'),
    path('control_history/', control_history, name='control_history'),
]

apps/forum/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.forum.views import index, show, tag, list, new_article


app_name = 'forum'
urlpatterns = [
    path('', index, name='index'),
    path('show-<int:sid>.html/', show, name='show'),
    path('tag/<tag>', tag, name='tags'),  # 标签列表页
    path('list-<int:lid>.html', list, name='list'),  # 列表页

    # path('new_article/', new_article, name='new_article'),
]

apps/monitor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.monitor.views import index, detail, get_data, query_environmentdata, add_data, analysis


app_name = 'monitor'
urlpatterns = [
    path('', index, name='index'),   # 监控首页
    path('<int:house_id>/', detail, name='detail'),  # 大棚详情页
    path('<int:house_id>/get_data/', get_data, name='get_data'),   # 获取实时数据
    path('query/environment_data/', query_environmentdata, name='environment_data'),  # 查询环境数据
    path('add_data/', add_data, name='add_data'),  # 数据接口
    path('analysis/', analysis, name='analysis'),  # 折线图
]

apps/user/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.user.views import register, log_in, index, log_out, userinfo, reset_password

app_name = 'user'
urlpatterns = [
    path('register', register, name='register'),
    path('login', log_in, name='login'),
    path('index', index, name='index'),
    path('logout', log_out, name='logout'),
    path('userinfo', userinfo, name='userinfo'),
    path('reset_password', reset_password, name='reset_password'),
    path('', index, name='password'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/logo.png' %}"/>
    <title>AHA智慧大棚管理系统</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">#}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<!-- 头部扩展 -->
{% block top %}
{% endblock top %}
</head>

<body>
{% block body %}
{% endblock body %}

<footer class="bg-primary navbar-fixed-bottom">
    <p class="text-center">版权所有&copy;AHA</p>
</footer>
{% block bottom-script %}
{% endblock bottom-script %}
</body>
</html>

templates/base_content.html
{% extends 'base.html' %}
{% load static %}
{% block top %}
    <link rel="stylesheet" href="{% static 'css/mmss.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel='stylesheet' href='{% static "css/style.css" %}' type='text/css' media='all'/>
    <script src="{% static 'js/html5shiv.min.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    {% block top-css %}
    {% endblock top-css %}
{% endblock top %}

{% block body %}
<header>
    <div class="container-fluid navbar-fixed-top bg-primary">
        <ul class="nav navbar-nav  left">
            <li class="text-white h4">
                &nbsp;<img src="{% static 'img/xinlogo.png' %}">&nbsp;&nbsp;<b>AHA智慧大棚管理系统</b>
            </li>
        </ul>
        {# 登录显示 #}
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav nav-pills right">
                        <li class="bg-danger">
                            <a href="#"><span class="glyphicon glyphicon-bell"></span></a>
                        </li>
                        <li class="dropdown bg-info" id="dropdownMenu1">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span>&nbsp;<span>{{ user.username }}</span><span
                                    class="caret"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                <li class="text-center"><a href="#"><span class="text-primary">账号设置</span></a></li>
                                <li class="text-center"><a href="#"><span class="text-primary">消息设置</span></a></li>
                                <li class="text-center"><a href="#"><span class="text-primary">帮助中心</span></a></li>
                                <li role="separator" class="divider"></li>
                                <li class="text-center"><a href="{% url 'user:logout' %}"><span
                                        class="text-primary">退出</span></a></li>
                            </ul>
                        </li>
                    </ul>
        {# 未登录显示 #}
                {% else %}
                    <ul class="nav navbar-nav nav-pills right">
                        <li class="bg-danger"><a href="{% url 'user:login' %}"><span>登录</span></a></li>
                        <li class="bg-danger"><a href="{% url 'user:register' %}"><span>注册</span></a></li>
                    </ul>
                {% endif %}
    </div>
</header>

<section>
    <div class="container-fluid">
        <div class="row ">
            <!--左侧导航开始-->
            <div class="col-xs-2 bg-blue">
                <br/>
                <div class="panel-group sidebar-menu" id="accordion" aria-multiselectable="true">
                    <div class="panel panel-default menu-first menu-first-active">
                        <!--<a href="index.html" data-toggle="collapse" data-parent="#accordion"  aria-expanded="true"
                           aria-controls="collapseOne">--><!--实现主页下可以折叠-->
                        <a href="{% url 'index' %}">
                            <i class="icon-home icon-large "></i> 主页
                        </a>
                    </div>
                    <div class="panel panel-default menu-first">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                           aria-expanded="true"
                           aria-controls="collapseOne">
                            <i class="icon-user-md icon-large"></i> 智慧大棚论坛</a>

                        <div id="collapseOne" class="panel-collapse  ">
                            <ul class="nav nav-list menu-second">
                                <li><a href="{% url 'forum:index' %}"><i class="icon-edit"></i>论坛首页</a></li>
                                <li><a href="{% url 'forum:index' %}list-1.html"><i class="icon-edit"></i>文章列表</a></li>
<!--                                <li><a href="write_message.html"><i class="icon-edit"></i>发布帖子</a></li>-->
                            </ul>
                        </div>
                    </div>
                    <div class="panel panel-default menu-first ">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                           href="#collapseTwo"
                           aria-expanded="false" aria-controls="collapseTwo">
                            <i class="icon-book icon-large"></i> 大棚管理</a>

                        <div id="collapseTwo" class="panel-collapse ">
                            <ul class="nav nav-list menu-second">
                                <li><a href="{% url 'monitor:index' %}"><i class="icon-star"></i> 环境监测</a></li>
                                <li><a href="{% url 'control:device_control' %}"><i class="icon-undo"></i> 设备控制</a></li>
                                <li><a href="{% url 'monitor:environment_data' %}"><i class="icon-glass"></i> 环境数据查询</a></li>
                                <li><a href="{% url 'monitor:analysis' %}"><i class="icon-search"></i> 数据分析</a></li>

                            </ul>
                        </div>
                    </div>
                    <div class="panel panel-default menu-first">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                           href="#collapseThree"
                           aria-expanded="false" aria-controls="collapseThree">
                            <i class="icon-book icon-large"></i> 个人中心</a>


                        <div id="collapseThree" class="panel-collapse ">
                            <ul class="nav nav-list menu-second">
                                <li><a href="{% url 'user:index' %}"><i class="icon-inbox"></i> 个人首页</a></li>
                                <li><a href="{% url 'user:userinfo' %}"><i class="icon-user"></i> 基本资料</a></li>
                                <li><a href="{% url 'user:reset_password' %}"><i class="icon-edit"></i> 密码修改</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--左侧导航结束-->
            <!--右侧内容开始-->
            {% block right-content %}
            {% endblock right-content %}
            <!--右侧内容结束-->
        </div>
    </div>
</section>
<!--左侧导航结束-->

{% endblock body %}